name: HIPAA Training System CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: hipaa-tests
  cancel-in-progress: false  # prevents GitHub from canceling previous runs

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # extend time limit

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Wait before testing (stabilize environment)
      run: sleep 5

    - name: Run tests with pytest
      run: PYTHONPATH=src pytest tests/ -v --disable-warnings
