    - name: Run tests with pytest
      env:
        PYTHONPATH: ${{ github.workspace }}/src
      run: |
        echo "Starting pytest..."
        timeout 120 pytest tests/ -v --disable-warnings || true
