name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with: { python-version: '3.10' }
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Initialize database
        run: python src/web/init_db.py
      - name: Run CLI tests
        run: python -m pytest tests/test_hipaa_training_v2.py -v
      - name: Run web tests
        run: python -m pytest tests/test_hipaa_web.py -v
