# .github/workflows/test.yml
name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with: { python-version: '3.8' }
    - name: Install dependencies
      run: pip install coverage
    - name: Run tests
      run: coverage run -m unittest test_hipaa_training.py
    - name: Report coverage
      run: coverage report
